name: 'Delete a Release'
description: 'Delete a release by its tag in your repository'
author: 'Jagger De Leo'
inputs:
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
outputs:
  id:
    description: 'The ID of the deleted Release'
  delete_response:
    description: 'The response from the DELETE action'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
